
TAG=['RECORD_TAG_GPS_HEAD','RECORD_TAG_GPS_DIFF','RECORD_TAG_SPORT_CADENCE','RECORD_TAG_SPORT_INFO']
CADENCETYPE=['CADENCE_TYPE_HERAT','CADENCE_TYPE_STEP','CADENCE_TYPE_STROKE','CADENCE_TYPE_BICYCLE']
DATA={'RECORD_TAG_GPS_HEAD':16,'RECORD_TAG_GPS_DIFF':8,'RECORD_TAG_SPORT_CADENCE':8,'RECORD_TAG_SPORT_INFO':8}
SPORT_TYPE=['RUNNING','SWIMMING','RIDING','INTERMITTEN_MOTION']
SPORT_STATE=['START','PAUSE','RESTART','ONE_CIRCLE','FINISH_SAVE','FINISH_DELETE','SPORT']